#' Summarise ERA5 Point Data from Downloaded NetCDF Files
#'
#' This function reads NetCDF files previously downloaded using
#' \code{download_era5()} and summarises each climate variable using a
#' user-defined function (e.g., \code{mean}, \code{sum}, \code{max}).
#' The function extracts latitude and longitude values automatically
#' from the filenames produced by \code{download_era5()}, which encode
#' coordinates in the format \code{"era5_<lat>_<lon>.nc"}.
#'
#' @param path Character. Directory containing the NetCDF files.
#'   Defaults to \code{"era5_downloads"}.
#'
#' @param variables Optional character vector specifying which ERA5
#'   variables to summarise. If \code{NULL} (default), all variables
#'   present in each NetCDF file are summarised.
#'
#' @param fun A function to apply for summarising the time dimension
#'   of each variable (e.g., \code{mean}, \code{sum}, \code{sd},
#'   or a user-defined custom function).
#'   Defaults to \code{mean}.
#'
#' @param ... Additional arguments passed to \code{fun}
#'   (e.g., \code{na.rm = TRUE}).
#'
#' @return A data frame where each row corresponds to one NetCDF file
#'   (i.e., one coordinate), containing:
#'   \itemize{
#'     \item{\code{lat}, \code{lon} — extracted coordinate values}
#'     \item{One column per climate variable summarised over the time window}
#'   }
#'
#' @details
#' This function assumes that NetCDF files follow the naming convention
#' generated by \code{download_era5()}, where latitude and longitude are
#' encoded as \code{"era5_<lat>_<lon>.nc"} with decimal points replaced
#' by underscores. For example:
#' \preformatted{
#'   era5_41_59146_-4_876213.nc
#' }
#'
#' Each file is read using the \pkg{terra} package, and the provided
#' summarising function is applied to the full time series of each
#' selected variable.
#'
#' @examples
#' \dontrun{
#' # Summarise all variables using the mean
#' df <- summarise_era5(
#'   path = "era5_downloads",
#'   fun = mean,
#'   na.rm = TRUE
#' )
#'
#' # Summarise only temperature and precipitation
#' df2 <- summarise_era5(
#'   variables = c("2m_temperature", "total_precipitation"),
#'   fun = sum,
#'   na.rm = TRUE
#' )
#'
#' # 95th percentile of temperature
#' df3 <- summarise_era5(
#'   variables = "2m_temperature",
#'   fun = function(x) quantile(x, 0.95, na.rm = TRUE)
#' )
#' }
#'
#' @export
summarise_era5 <- function(path = "era5_downloads",
                           variables = NULL,
                           fun = mean,
                           ...) {
  
  requireNamespace("terra", quietly = TRUE)
  requireNamespace("dplyr", quietly = TRUE)
  requireNamespace("stringr", quietly = TRUE)
  requireNamespace("purrr", quietly = TRUE)
  
  # List NetCDF files
  files <- list.files(path, pattern = "\\.nc$", full.names = TRUE)
  if (length(files) == 0)
    stop("No NetCDF files found in directory: ", path)
  
  # Helper: extract numeric lat/lon from filenames
  parse_coords <- function(f) {
    # example: "era5_41_59146_-4_876213.nc"
    base <- basename(f)
    cleaned <- gsub("era5_|\\.nc", "", base)
    parts <- strsplit(cleaned, "_")[[1]]
    
    # lat and lon were stored as:  "41_59146", "-4_876213"
    lat_str <- paste(parts[1], parts[2], sep = ".")
    lon_str <- paste(parts[3], parts[4], sep = ".")
    
    data.frame(
      lat = as.numeric(lat_str),
      lon = as.numeric(lon_str)
    )
  }
  
  # Read & summarise each file
  result_list <- purrr::map(files, function(f) {
    
    coords <- parse_coords(f)
    
    r <- terra::rast(f)
    
    # Select only variables requested
    if (!is.null(variables)) {
      missing_vars <- setdiff(variables, names(r))
      if (length(missing_vars) > 0)
        warning("Variables not found in ", f, ": ",
                paste(missing_vars, collapse = ", "))
      
      r <- r[[intersect(variables, names(r))]]
    }
    
    # Apply summarising function to each layer
    vals <- purrr::map_dbl(names(r), function(v) {
      fun(terra::values(r[[v]]), ...)  # allows na.rm = TRUE, etc.
    })
    
    data.frame(
      lat = coords$lat,
      lon = coords$lon,
      t(vals)
    )
  })
  
  # Combine into a single data frame
  results <- dplyr::bind_rows(result_list)
  
  # Convert temperature variables from Kelvin to Celsius
  kelvin_vars <- c("t2m", "2m_temperature")
  
  for (kv in kelvin_vars) {
    if (kv %in% names(results)) {
      results[[kv]] <- results[[kv]] - 273.00
    }
  }
  
  return(results)
  
}




## expected path to the nc we asked for
#expected_nc <- paste0(temp_dir, "/", out_file)
#
## read the (one or many) netcdf(s)
#r <- terra::rast(expected_nc)
#
## extract values at the single point (returns 1 row)
#extracted <- terra::extract(r, data.frame(lon = lon, lat = lat))
#
## drop ID column
#values <- extracted[, -1, drop = FALSE]
#summary_values <- apply(values, 1, summarise_fun, na.rm = TRUE) 
#
## Build final output data.frame: one column per variable (group)
#out <- data.frame(
#  start_date = start_date,
#  end_date = end_date,
#  lat = lat,
#  lon = lon)
#
#out <- dplyr::tibble(out, !!variables := summary_values)
#rownames(out) <- NULL
#return(out)
#
